# Generated by Django 5.0.4 on 2024-04-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("picture", models.ImageField(upload_to="restaurants/")),
                ("rating", models.FloatField()),
                ("criteria", models.CharField(max_length=200)),
                ("area", models.CharField(max_length=100)),
            ],
        ),
    ]
