# Generated by Django 5.0.4 on 2024-04-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0005_fooditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="phone_number",
            field=models.IntegerField(max_length=11, null=True, unique=True),
        ),
    ]
