# Generated by Django 5.0.4 on 2024-04-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0006_userinfo_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="phone_number",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
