# Generated by Django 5.0.4 on 2024-05-06 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0009_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
