# Generated by Django 5.0.4 on 2024-05-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0011_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryMan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("phone_number", models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
