# Generated by Django 5.0.4 on 2024-05-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0012_deliveryman"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
