# Generated by Django 5.0.4 on 2024-05-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0014_remove_order_food_item_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="service.location",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_bill",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price_with_vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
