# Generated by Django 5.0.4 on 2024-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0015_order_location_order_total_bill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[("Regular", "Regular"), ("DeliveryMan", "Delivery Man")],
                default="Regular",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=6
            ),
        ),
    ]
