# Generated by Django 5.0.4 on 2024-05-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0018_remove_finaldelivery_accepted_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
